language: elixir
sudo: false

elixir:
  - 1.6.4

otp_release:
  - 20.1

notifications:
  recipients:
    - areski@gmail.com

script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
