FROM jessie_elixir16
# replaced by custom image using Jessie
# FROM elixir:1.6.6

MAINTAINER Areski <areski@gmail.com>

ENV REFRESHED_AT 2018-07-09
# 2017-01-15 update to elixir 1.6.6

# Install hex
RUN /usr/local/bin/mix local.hex --force && \
    /usr/local/bin/mix local.rebar --force && \
    /usr/local/bin/mix hex.info

WORKDIR /app
COPY . .

RUN mix deps.get

CMD ["bash"]